name: Actualizar listado de diputados

on:
  push:
    branches: [main]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurar R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.2'

    - name: Instalar paquetes de R
      run: |
        Rscript -e 'install.packages(c("rvest", "tidyverse"))'

    - name: Ejecutar codigo.R
      run: |
        ls
        Rscript extraccion_diputados.R.R

    - name: Commit cambios
      uses: EndBug/add-and-commit@v7
      with:
        author_name: sientifiko
        author_email: socialscienceanime@gmail.com
        message: "Actualización de diputados"
