name: Actualizar listado de diputados
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.2'
        
    - name: Run R script
      run: |
        R -e "install.packages(c('tidyverse', 'rvest'))"
        Rscript extraccion_diputados.R
        
    - name: Commit results
      run: |
        git config --global user.email "socialscienceanime@gmail.com"
        git config --global user.name "sientifiko"
        git add .
        git commit -m "Add results"
        git push
